version: '3.8'

services:
  redpanda:
    image: vectorized/redpanda:latest
    volumes:
      - ./redpanda-init.sh:/redpanda-init.sh
    entrypoint:
      - sh
      - /redpanda-init.sh
    ports:
      - 9092:9092
      - 29092:29092
