// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	client "github.com/ch629/go-irc-kafka/irc/client"
	mock "github.com/stretchr/testify/mock"

	parser "github.com/ch629/go-irc-kafka/irc/parser"
)

// IRCReadWriter is an autogenerated mock type for the IRCReadWriter type
type IRCReadWriter struct {
	mock.Mock
}

// Input provides a mock function with given fields:
func (_m *IRCReadWriter) Input() <-chan parser.Message {
	ret := _m.Called()

	var r0 <-chan parser.Message
	if rf, ok := ret.Get(0).(func() <-chan parser.Message); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan parser.Message)
		}
	}

	return r0
}

// Send provides a mock function with given fields: messages
func (_m *IRCReadWriter) Send(messages ...client.IrcMessage) error {
	_va := make([]interface{}, len(messages))
	for _i := range messages {
		_va[_i] = messages[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(...client.IrcMessage) error); ok {
		r0 = rf(messages...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
