// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	domain "github.com/ch629/go-irc-kafka/pkg/domain"
	mock "github.com/stretchr/testify/mock"
)

// Producer is an autogenerated mock type for the Producer type
type Producer struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *Producer) Close() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendBan provides a mock function with given fields: ban
func (_m *Producer) SendBan(ban domain.Ban) error {
	ret := _m.Called(ban)

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.Ban) error); ok {
		r0 = rf(ban)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendChatMessage provides a mock function with given fields: message
func (_m *Producer) SendChatMessage(message domain.ChatMessage) error {
	ret := _m.Called(message)

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.ChatMessage) error); ok {
		r0 = rf(message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
