// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// IsInChannel provides a mock function with given fields: channelName
func (_m *Service) IsInChannel(channelName string) bool {
	ret := _m.Called(channelName)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(channelName)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// JoinChannel provides a mock function with given fields: channelName
func (_m *Service) JoinChannel(channelName string) {
	_m.Called(channelName)
}

// LeaveChannel provides a mock function with given fields: channelName
func (_m *Service) LeaveChannel(channelName string) error {
	ret := _m.Called(channelName)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(channelName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
